services:
  dev-db:
    image: mongo:8
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 173314
    networks:
      - todolist

networks:
  todolist:
